name: Run tests

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    name: Run Maven Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      
      - name: Run Maven Tests
        run: mvn test
